'use strict';
// Only inspect the already sealed wire's producer capture grammar; no render gate.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),product=path.resolve(process.argv[2]),output=path.resolve(process.argv[3]);assert(!fs.existsSync(output));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),cache=JSON.parse(fs.readFileSync(path.join(product,'candidate-cache.json'),'utf8'));
const selected=cache.config_matrix.filter(r=>r.config.game_language==='en'&&r.config.primary==='en'&&r.config.secondary==='zh-Hans');assert.equal(selected.length,1);
const wire=path.join(product,'generated',selected[0].wire_name),stat=fs.statSync(wire),bytes=fs.readFileSync(wire);assert.equal(sha(bytes),selected[0].wire_sha256);
const script=path.join(root,'sora_bilingual/game/scripts/runtime_text.js'),scriptHash=sha(fs.readFileSync(script)),{RuntimeText}=require(script);
const loader=new Function('rpc',fs.readFileSync(path.join(product,'sora_bilingual/game/scripts/native_transport.js'),'utf8')+';return readIndexedModel;')({exports:{}}),model=loader(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));
function captures(source){const tokens=[];for(let i=0;i<source.length;i++){if(source[i]==='\\'){i++;continue;}if(source[i]!=='('||source[i+1]==='?')continue;const start=i;let depth=1,inside=false;while(++i<source.length){const c=source[i];if(c==='\\'){i++;continue;}if(c==='['){inside=true;continue;}if(c===']'){inside=false;continue;}if(inside)continue;if(c==='(')depth++;if(c===')'&&!--depth)break;}assert.equal(depth,0);tokens.push(source.slice(start,i+1));}return tokens;}
const types=new Map(),rows=(model.producer_numeric||[]).map(([pattern,pair,styles],index)=>{const tokens=captures(pattern);for(const token of tokens){const r=types.get(token)||{token,occurrences:0,rows:[],examples:[]};r.occurrences++;if(!r.rows.includes(index)){r.rows.push(index);if(r.examples.length<2)r.examples.push({index,pattern,pair,styles});}types.set(token,r);}return {index,pattern,pair,styles,captures:tokens,current_required_literal:RuntimeText.numericLiteral(pattern)};});
const compiled=rows.map(r=>[new RegExp('^(?:'+r.pattern+')$'),r.pair,r.styles]),allTokens=[...types.keys()];
// A conservative index-only proposal: recognised complete generated captures
// become the already supported wildcard capture solely for literal extraction.
// The original matching regex, parameter checks, order and output stay unchanged.
const proposedPatterns=rows.map(row=>[allTokens.reduce((p,token)=>p.split(token).join('([^<>\\r\\n]{0,512}?)'),row.pattern)]),proposedIndex=RuntimeText.numericIndex(compiled,proposedPatterns),witnessCache=new Map(),witnessValues=['0','1','-1','2147483647','-2147483648','０','１','－１'];let matches=0;const misses=[];
for(const row of rows)for(const value of witnessValues){let source=row.pattern;for(const token of row.captures)source=source.replace(token,value);source=source.replace(/\\([^A-Za-z0-9])/g,'$1');if(!compiled[row.index][0].test(source))continue;matches++;if(!RuntimeText.numericCandidates(source,proposedIndex,witnessCache).includes(compiled[row.index]))misses.push({index:row.index,source,pattern:row.pattern});}
const parameterKinds={};for(const row of model.details?.detail_effect_units||[])for(const kind of row.parameter_kinds||[])parameterKinds[kind]=(parameterKinds[kind]||0)+1;
const report={schema:1,kind:'sealed local8 producer capture metadata and conservative required-literal proof; no implementation or render benchmark',wire_path:wire,wire_sha256:selected[0].wire_sha256,working_script_path:script,working_script_sha256:scriptHash,working_script_stable:sha(fs.readFileSync(script))===scriptHash,producer_rows:rows.length,capture_types:[...types.values()],parameter_kind_field_occurrences:parameterKinds,all_rows:rows,proposed_index_fallback:proposedIndex.fallback.length,proposed_matching_witness_count:matches,proposed_missing_candidates:misses,proposal_constraint:'Only explicitly registered exact complete capture tokens may be skipped by numericLiteral. All other syntax must retain ordered fallback; original RegExp and formatting are unchanged. This in-memory metadata proof does not patch production.',package_wire_size_mtime_unchanged:fs.statSync(wire).size===stat.size&&fs.statSync(wire).mtimeMs===stat.mtimeMs,game_read:false,game_attached:false,production_modified:false,compiled:false,build_run:false,checker_sha256:sha(fs.readFileSync(__filename))};
assert(report.package_wire_size_mtime_unchanged);fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({output,sha256:sha(fs.readFileSync(output)),producer_rows:rows.length,capture_types:[...types.values()].map(r=>({token:r.token,occurrences:r.occurrences,rows:r.rows.length,example:r.examples[0]})),parameterKinds,proposed_index_fallback:report.proposed_index_fallback,proposed_matching_witness_count:matches,proposed_missing_candidates:misses.length}));
