'use strict';
// Count parser work on captured full inputs. The default preserves the exact
// local8 baseline contract; --receipt explicitly validates a newer full wire.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {performance}=require('node:perf_hooks');
const root=path.resolve(__dirname,'..'),receiptMode=process.argv[2]==='--receipt',options={};
if(receiptMode){const fields={'--receipt':'receipt','--freeze':'freeze','--snapshot-sha256':'snapshot','--capture':'capture','--output':'output','--input':'input','--runtime-root':'runtimeRoot'};for(let i=2;i<process.argv.length;i++){assert(fields[process.argv[i]],'unknown argument '+process.argv[i]);options[fields[process.argv[i]]]=process.argv[++i];}for(const key of ['receipt','freeze','snapshot','capture','output','input'])assert(options[key],key+' required');}
const product=receiptMode?null:path.resolve(process.argv[2]),capturePath=path.resolve(receiptMode?options.capture:process.argv[3]),output=path.resolve(receiptMode?options.output:process.argv[4]);
assert(!fs.existsSync(output),'preserve all previous receipts');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),json=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const scripts=path.join(receiptMode?path.resolve(options.runtimeRoot||root):product,'sora_bilingual/game/scripts'),runtimePath=path.join(scripts,'runtime_text.js'),transportPath=path.join(scripts,'native_transport.js'),runtimeHash=sha(fs.readFileSync(runtimePath));
const receipt=receiptMode?json(options.receipt):null,freeze=receiptMode?json(options.freeze):null,receiptHash=receiptMode?sha(fs.readFileSync(options.receipt)):null,freezeHash=receiptMode?sha(fs.readFileSync(options.freeze)):null;
let cache,selected,wirePath;
if(receiptMode){assert.equal(freeze.snapshot_sha256,options.snapshot);assert.equal(receipt.source_snapshot_sha256,options.snapshot);assert.equal(runtimeHash,freeze.files['sora_bilingual/game/scripts/runtime_text.js']);assert.equal(receipt.config.game_language,'en');assert.equal(receipt.config.primary,'en');assert.equal(receipt.config.secondary,'zh-Hans');assert.equal(sha(fs.readFileSync(receipt.model_path)),receipt.model_sha256);cache={source_snapshot_sha256:options.snapshot};selected=[{wire_sha256:receipt.wire_sha256}];wirePath=path.resolve(receipt.wire_path);}
else{cache=json(path.join(product,'candidate-cache.json'));selected=cache.config_matrix.filter(r=>r.config.game_language==='en'&&r.config.primary==='en'&&r.config.secondary==='zh-Hans');assert.equal(selected.length,1);wirePath=path.join(product,'generated',selected[0].wire_name);}
const wireBefore=fs.statSync(wirePath,{bigint:true}),bytes=fs.readFileSync(wirePath);assert.equal(sha(bytes),selected[0].wire_sha256);
const capture=json(capturePath),inputs=[...new Set(capture.rows.filter(r=>r.source_matches_diagnostic&&['success_info','unique_info','failure_info'].some(k=>r.input_identity_diagnostic?.node_path?.includes(k))).map(r=>r.original))];
const parentPath=path.join(root,'generated/r32-live008-recipe-resolve-node-before.json'),parent=json(parentPath);assert.deepEqual(inputs,parent.rows.map(r=>r.input));
if(!receiptMode){assert.equal(parent.source_snapshot_sha256,cache.source_snapshot_sha256);assert.equal(parent.wire_sha256,selected[0].wire_sha256);assert.equal(parent.runtime_text_sha256,runtimeHash);}
const model=new Function('rpc',fs.readFileSync(transportPath,'utf8')+';return readIndexedModel;')({exports:{}})(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));
const {RuntimeText}=require(runtimePath),baseline=new RuntimeText(model),baselines=[];
const primaryText=text=>text.replace(/<R>(.*?)<\/R[^<>]*>/gs,'$1');
function secondaryText(plan){if(!plan.layers.length)return plan.text.replace(/<R>(.*?)<\/R([^<>]*)>/gs,(_m,a,b)=>a?b:'');let text=plan.text,at=0;for(const layer of plan.layers){const anchor=text.indexOf('<R></R_>',at);assert(anchor>=0&&text.startsWith(layer.primary,anchor+8));text=text.slice(0,anchor)+layer.text+text.slice(anchor+8+layer.primary.length);at=anchor+layer.text.length;}return primaryText(text);}
function semantics(text){const parts=text.normalize('NFKC').split(/(\r\n|\n|\\n)/);parts[0]=parts[0].replace(/\s+-\s+/g,'').replace(/[\[\]()【】:：/・･、]/g,'');return parts.join('').replace(/<\/?[Cc][0-9a-fA-F]*>|<[sS]\d+>/g,'').replace(/\s/gu,'');}
const fixture=receiptMode?json(options.input):null;
function expectedHeader(input){if(!receiptMode)return null;const matches=fixture.cases.filter(c=>c.locale==='en'&&c.original_source===input),pairs=matches.map(c=>[c.texts.en.split('\n')[0],c.texts['zh-Hans'].split('\n')[0]]);if(pairs.length){assert.equal(new Set(pairs.map(p=>JSON.stringify(p))).size,1,'complete official target conflict');return {pair:pairs[0],item_ids:[...new Set(matches.map(c=>c.item_id))],origin:'unchanged full-body native9 fixture exact complete header'};}if(Object.hasOwn(model.pairs,input))return {pair:model.pairs[input],origin:'exact complete indexed-wire pair'};return null;}
for(const input of inputs){let before=performance.now();const cold=baseline.render(input,'annotation'),coldMs=performance.now()-before;before=performance.now();const warm=baseline.render(input,'annotation'),warmMs=performance.now()-before;
 assert.deepEqual(cold,warm);if(!receiptMode)assert.deepEqual(cold,parent.rows.find(r=>r.input===input).plan);
 const expected=expectedHeader(input),modes={annotation:{plan:cold,coldMs,warmMs}};
 if(receiptMode)for(const mode of ['primary','secondary']){before=performance.now();const plan=baseline.render(input,mode),firstMs=performance.now()-before;before=performance.now();const repeated=baseline.render(input,mode),repeatMs=performance.now()-before;assert.deepEqual(plan,repeated);modes[mode]={plan,coldMs:firstMs,warmMs:repeatMs};}
 if(receiptMode)for(const [mode,entry] of Object.entries(modes)){const comparisons=[[primaryText(entry.plan.text),mode==='secondary'?expected?.pair[1]:expected?.pair[0]]];if(mode==='annotation')comparisons.push([secondaryText(entry.plan),expected?.pair[1]]);entry.comparison={strict_equal:expected?comparisons.every(([a,b])=>a===b):null,complete_semantics_equal:expected?comparisons.every(([a,b])=>semantics(a)===semantics(b)):null,normal_primary_source_exact:mode==='secondary'||primaryText(entry.plan.text)===input};}
 baselines.push({input,coldMs,warmMs,cold_plan:cold,warm_plan:warm,old_preserved_plan:parent.rows.find(r=>r.input===input).plan,plan_equals_old_preserved:JSON.stringify(cold)===JSON.stringify(parent.rows.find(r=>r.input===input).plan),official_expected:expected,modes});}
const profiled=new RuntimeText(model),identities=new WeakMap(),regexLabels=new WeakMap(),indexLabels=new WeakMap();let instance=0,active=null;
function register(tr,name){if(identities.has(tr))return;identities.set(tr,name+'#'+(++instance));
 for(const [field,kind] of [['detailEffectUnits','effect_strict'],['detailEffectDirectionGuards','direction_guards'],['detailEffectBlockedNumeric','effect_blocked'],['numeric','numeric'],['rawNumeric','raw_numeric'],['producerNumeric','producer_numeric'],['detailNumeric','detail_numeric'],['detailInlineIcons','inline_icons'],['resourceFormatterPatterns','resource_formatters']])
  for(const row of tr[field]||[]){const regex=row instanceof RegExp?row:row.find?.(r=>r instanceof RegExp);if(regex)regexLabels.set(regex,{resolver:identities.get(tr),kind});}
 for(const [field,kind] of [['detailEffectUnitIndex','effect_strict'],['detailEffectParameterGuards','parameter_guards'],['numericIndex','numeric'],['detailNumericIndex','detail_numeric'],['detailInlineIconIndex','inline_icons'],['rawNumericIndex','raw_numeric'],['producerNumericIndex','producer_numeric']]){
  if(tr[field])indexLabels.set(tr[field],{resolver:identities.get(tr),kind});
  if(field==='detailEffectParameterGuards')for(const e of [...(tr[field]?.fallback||[]),...[...(tr[field]?.byFirst?.values()||[])].flatMap(b=>[...b.values()].flat())]){
   const regex=e.rule?.find?.(r=>r instanceof RegExp);if(regex)regexLabels.set(regex,{resolver:identities.get(tr),kind});}}
 if(tr.details)register(tr.details,name+'.details');for(const [key,child] of Object.entries(tr.scoped||{}))register(child,name+'.scoped.'+key);for(const [key,child] of Object.entries(tr.keyed||{}))register(child.tr,name+'.keyed.'+key);
}
register(profiled,'root');
const methods=['render','translate','resolve','effectDetailPlan','itemHelpHeader','skillHeader','effectUnits','effectUnit','effectLineUnits','rawPair','wholeConflict','detailBodyBoundary','conditionListUnit'];
const originals={};
for(const name of methods){const original=RuntimeText.prototype[name];if(typeof original!=='function')continue;originals[name]=original;
 RuntimeText.prototype[name]=function(...args){if(!active)return original.apply(this,args);const p=active,resolver=identities.get(this)||'other',at=performance.now(),frame={name,resolver,nested:0},caller=p.stack.at(-1)?.name||'entry';
  p.stack.push(frame);let result;try{result=original.apply(this,args);return result;}finally{const elapsed=performance.now()-at;p.stack.pop();if(p.stack.length)p.stack.at(-1).nested+=elapsed;
   const bucket=p.methods[name]||(p.methods[name]={calls:0,inclusiveMs:0,exclusiveMs:0,maxMs:0});bucket.calls++;bucket.inclusiveMs+=elapsed;bucket.exclusiveMs+=elapsed-frame.nested;bucket.maxMs=Math.max(bucket.maxMs,elapsed);
   if(['effectUnit','effectUnits','itemHelpHeader','effectDetailPlan'].includes(name)){
    const arg={resolver,source:args[0],...(name==='effectUnit'?{coalesced:args[1]===true}:{}),...(name==='effectUnits'?{allowOpaque:args[1]===true,description:args[2]||'',join:args[3]||this.detailJoin,ownedUnits:!!args[4]}:{}),...(name==='effectDetailPlan'?{mode:args[2]||'annotation',owner_present:!!args[1]}:{})};
    const key=JSON.stringify([name,arg]),row=p.calls.get(key)||{method:name,args:arg,calls:0,callers:{},returned_null:0,failure_reasons:{}};row.calls++;row.callers[caller]=(row.callers[caller]||0)+1;if(result==null)row.returned_null++;
    const reason=this.effectUnitFailures?.get(args[0]);if(reason)row.failure_reasons[reason]=(row.failure_reasons[reason]||0)+1;p.calls.set(key,row);
    if(name==='effectUnits')p.effect_units_invocations.push({args:arg,result:result??null,reason:reason??null});
   }
  }};
}
const originalCandidates=RuntimeText.numericCandidates;
RuntimeText.numericCandidates=function(source,index,cache){const result=originalCandidates.call(this,source,index,cache);if(active){const tag=indexLabels.get(index),key=JSON.stringify([tag,source]),r=active.candidates.get(key)||{tag,source,calls:0,selected_rule_count:result.length};r.calls++;active.candidates.set(key,r);}return result;};
const originalExec=RegExp.prototype.exec;
RegExp.prototype.exec=function(source){if(!active)return originalExec.call(this,source);const result=originalExec.call(this,source),tag=regexLabels.get(this)||{resolver:active.stack.at(-1)?.resolver||'unknown',kind:'literal_or_dynamic'},key=this.source+'\u0000'+this.flags+'\u0000'+tag.resolver+'\u0000'+tag.kind;
 const r=active.regex.get(key)||{pattern:this.source,flags:this.flags,...tag,calls:0,matches:0,callers:{}};r.calls++;if(result)r.matches++;const caller=active.stack.at(-1)?.name||'entry';r.callers[caller]=(r.callers[caller]||0)+1;active.regex.set(key,r);return result;};
function sizes(tr){return {plan:tr.planCache.size,translate:tr.cache.size,details_effect_candidates:tr.details?.detailEffectUnitCandidateCache.size,details_parameter_candidates:tr.details?.detailEffectParameterGuardCache.size};}
const stages=[];
try{for(const input of inputs)for(const temperature of ['first','same_input_repeat']){const before=sizes(profiled),p={stack:[],methods:{},calls:new Map(),regex:new Map(),candidates:new Map(),effect_units_invocations:[]};active=p;
 const at=performance.now(),plan=profiled.render(input,'annotation'),elapsed=performance.now()-at;active=null;assert.deepEqual(plan,baselines.find(r=>r.input===input).cold_plan);
 const categories={};for(const row of p.regex.values()){const key=row.resolver+'/'+row.kind,category=categories[key]||(categories[key]={calls:0,matches:0,distinctPatterns:0});category.calls+=row.calls;category.matches+=row.matches;category.distinctPatterns++;}
 const calls=[...p.calls.values()],duplicates=Object.fromEntries(['effectUnit','effectUnits','itemHelpHeader','effectDetailPlan'].map(name=>{const rows=calls.filter(r=>r.method===name);return[name,{total_calls:rows.reduce((a,r)=>a+r.calls,0),unique_exact_arguments:rows.length,repeated_exact_calls:rows.reduce((a,r)=>a+Math.max(0,r.calls-1),0)}];}));
 stages.push({input,temperature,instrumentedMs:elapsed,cache_before:before,cache_after:sizes(profiled),plan,methods:p.methods,duplicates,regexp_categories:categories,
  regexp_patterns:[...p.regex.values()].sort((a,b)=>b.calls-a.calls),numeric_candidate_requests:[...p.candidates.values()],exact_argument_calls:calls.sort((a,b)=>b.calls-a.calls),effect_units_invocations:p.effect_units_invocations});
 }}finally{active=null;RegExp.prototype.exec=originalExec;RuntimeText.numericCandidates=originalCandidates;for(const [name,original] of Object.entries(originals))RuntimeText.prototype[name]=original;}
const ruleCounts={root:{strict:profiled.detailEffectUnits.length,direction:profiled.detailEffectDirectionGuards.length},details:{strict:profiled.details.detailEffectUnits.length,direction:profiled.details.detailEffectDirectionGuards.length,compact_rows:profiled.itemHelpHeaders.compact_rows.length,attack_rows:profiled.itemHelpHeaders.attack_rows.length}};
let guardWitnesses=null,indexCounts=null;
if(receiptMode){const index=profiled.details.detailEffectParameterGuards,entries=[...index.fallback,...[...index.byFirst.values()].flatMap(b=>[...b.values()].flat())].sort((a,b)=>a.at-b.at),candidateCache=new Map(),values=['','UNKNOWN','2.5','0','+1','-1','0001','2147483648','4294967295','4294967296',' - ','<X998>'],misses=[];let matched=0,total=0;const parameterKinds={};for(const entry of entries){const [row,rx]=entry.rule;for(const kind of row.parameter_kinds||[])parameterKinds[kind]=(parameterKinds[kind]||0)+1;for(const value of values){const source=RuntimeText.renderFormat(row.source,()=>value);total++;if(!rx.test(source))continue;matched++;if(!RuntimeText.numericCandidates(source,index,candidateCache).includes(entry.rule))misses.push({source,row_source:row.source,pattern:rx.source});}}guardWitnesses={rows:entries.length,parameter_kind_field_occurrences:parameterKinds,witnesses:total,matching_witnesses:matched,missing_candidates:misses,test_values_only:true};indexCounts=Object.fromEntries([['parameter_guards',index],['strict_effect',profiled.details.detailEffectUnitIndex],['raw_numeric',profiled.rawNumericIndex],['producer_numeric',profiled.producerNumericIndex]].map(([name,i])=>[name,{total:i.fallback.length+[...i.byFirst.values()].flatMap(b=>[...b.values()].flat()).length,fallback:i.fallback.length,literals:[...i.byFirst.values()].reduce((a,b)=>a+b.size,0)}]));}
const report={schema:1,kind:receiptMode?'read-only source9 exact full production wire recipe parser counts':'read-only local8 recipe parser counts; no production optimization',product_root:product,source_snapshot_sha256:cache.source_snapshot_sha256,wire_path:wirePath,wire_sha256:selected[0].wire_sha256,
 runtime_text_sha256:runtimeHash,capture_path:capturePath,capture_sha256:sha(fs.readFileSync(capturePath)),parent_node_before_path:parentPath,parent_node_before_sha256:sha(fs.readFileSync(parentPath)),
 actual_input_provenance:capture.rows.filter(r=>inputs.includes(r.original)).map(r=>({original:r.original,source_matches_diagnostic:r.source_matches_diagnostic,input_identity_diagnostic:r.input_identity_diagnostic})),rule_counts:ruleCounts,uninstrumented_baselines:baselines,instrumented_stages:stages,
 output_full_plan_parity_with_preserved_baseline:baselines.every(r=>r.plan_equals_old_preserved),receipt_path:receiptMode?path.resolve(options.receipt):null,receipt_sha256:receiptHash,model_path:receipt?.model_path||null,model_sha256:receipt?.model_sha256||null,freeze_path:receiptMode?path.resolve(options.freeze):null,freeze_sha256:freezeHash,official_fixture_path:receiptMode?path.resolve(options.input):null,official_fixture_sha256:receiptMode?sha(fs.readFileSync(options.input)):null,indices:indexCounts,guard_witnesses:guardWitnesses,
 complete_mode_plan_count:receiptMode?baselines.length*3:baselines.length,complete_semantic_failure_count:receiptMode?baselines.reduce((n,r)=>n+Object.values(r.modes).filter(v=>v.comparison.complete_semantics_equal===false).length,0):null,unresolved_official_expectations:receiptMode?baselines.filter(r=>!r.official_expected).map(r=>r.input):[],instrumentation_limit:'RegExp/method instrumentation adds substantial overhead; instrumented timings are not performance acceptance. First render means resolver first complete plan; other modes may share candidate caches. Uninstrumented Node timings are separate from captured game callbacks.',
 package_wire_size_mtime_unchanged:fs.statSync(wirePath,{bigint:true}).size===wireBefore.size&&fs.statSync(wirePath,{bigint:true}).mtimeNs===wireBefore.mtimeNs,game_read:false,game_attached:false,production_modified:false,build_run:false,checker_sha256:sha(fs.readFileSync(__filename))};
assert(report.package_wire_size_mtime_unchanged);assert.equal(sha(fs.readFileSync(runtimePath)),runtimeHash);if(receiptMode){assert.equal(sha(fs.readFileSync(options.receipt)),receiptHash);assert.equal(sha(fs.readFileSync(options.freeze)),freezeHash);}fs.writeFileSync(output,JSON.stringify(report,null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({output,sha256:sha(fs.readFileSync(output)),ruleCounts,baseline:baselines.map(r=>({input:r.input,coldMs:r.coldMs,warmMs:r.warmMs,plan_equals_old_preserved:r.plan_equals_old_preserved,official_expected:r.official_expected})),indices:indexCounts,guard_witnesses:guardWitnesses,complete_semantic_failure_count:report.complete_semantic_failure_count,unresolved_official_expectations:report.unresolved_official_expectations,stages:stages.map(s=>({input:s.input,temperature:s.temperature,duplicates:s.duplicates,regexp_categories:s.regexp_categories,cache_before:s.cache_before,cache_after:s.cache_after}))}));
if(receiptMode)process.exitCode=report.complete_semantic_failure_count||guardWitnesses.missing_candidates.length||report.unresolved_official_expectations.length?1:0;
