'use strict';
// Shared pure resolver: runs synchronously inside the native label callback.
// No RPC, timers, pointers, filesystem access, or fuzzy substring matching.
const PRINTF_TOKEN=/%%|%(?:\d+\$)?[-+0 #]*\d*(?:\.\d+)?[diusg]/g;
const COMPONENT_SEPARATORS=/(\r\n|\n|\\n|[【】「」：:／/\[\]()]| - |[ \u3000]{2,})/;
const COMPONENT_LINKS=/([·・･])/;
// Unicode 16.0.0 letter/number ranges, generated by Python str.isalnum.
// Frida V8 has no Unicode property escapes. One shared table also handles
// unseen punctuation in printf slots; enumerating dictionary strings cannot.
const ALPHANUMERIC_RANGES=[
48,57,65,90,97,122,170,170,178,179,181,181,185,186,188,190,192,214,216,246,248,705,710,721,
736,740,748,748,750,750,880,884,886,887,890,893,895,895,902,902,904,906,908,908,910,929,931,1013,
1015,1153,1162,1327,1329,1366,1369,1369,1376,1416,1488,1514,1519,1522,1568,1610,1632,1641,1646,1647,1649,1747,1749,1749,
1765,1766,1774,1788,1791,1791,1808,1808,1810,1839,1869,1957,1969,1969,1984,2026,2036,2037,2042,2042,2048,2069,2074,2074,
2084,2084,2088,2088,2112,2136,2144,2154,2160,2183,2185,2190,2208,2249,2308,2361,2365,2365,2384,2384,2392,2401,2406,2415,
2417,2432,2437,2444,2447,2448,2451,2472,2474,2480,2482,2482,2486,2489,2493,2493,2510,2510,2524,2525,2527,2529,2534,2545,
2548,2553,2556,2556,2565,2570,2575,2576,2579,2600,2602,2608,2610,2611,2613,2614,2616,2617,2649,2652,2654,2654,2662,2671,
2674,2676,2693,2701,2703,2705,2707,2728,2730,2736,2738,2739,2741,2745,2749,2749,2768,2768,2784,2785,2790,2799,2809,2809,
2821,2828,2831,2832,2835,2856,2858,2864,2866,2867,2869,2873,2877,2877,2908,2909,2911,2913,2918,2927,2929,2935,2947,2947,
2949,2954,2958,2960,2962,2965,2969,2970,2972,2972,2974,2975,2979,2980,2984,2986,2990,3001,3024,3024,3046,3058,3077,3084,
3086,3088,3090,3112,3114,3129,3133,3133,3160,3162,3165,3165,3168,3169,3174,3183,3192,3198,3200,3200,3205,3212,3214,3216,
3218,3240,3242,3251,3253,3257,3261,3261,3293,3294,3296,3297,3302,3311,3313,3314,3332,3340,3342,3344,3346,3386,3389,3389,
3406,3406,3412,3414,3416,3425,3430,3448,3450,3455,3461,3478,3482,3505,3507,3515,3517,3517,3520,3526,3558,3567,3585,3632,
3634,3635,3648,3654,3664,3673,3713,3714,3716,3716,3718,3722,3724,3747,3749,3749,3751,3760,3762,3763,3773,3773,3776,3780,
3782,3782,3792,3801,3804,3807,3840,3840,3872,3891,3904,3911,3913,3948,3976,3980,4096,4138,4159,4169,4176,4181,4186,4189,
4193,4193,4197,4198,4206,4208,4213,4225,4238,4238,4240,4249,4256,4293,4295,4295,4301,4301,4304,4346,4348,4680,4682,4685,
4688,4694,4696,4696,4698,4701,4704,4744,4746,4749,4752,4784,4786,4789,4792,4798,4800,4800,4802,4805,4808,4822,4824,4880,
4882,4885,4888,4954,4969,4988,4992,5007,5024,5109,5112,5117,5121,5740,5743,5759,5761,5786,5792,5866,5870,5880,5888,5905,
5919,5937,5952,5969,5984,5996,5998,6000,6016,6067,6103,6103,6108,6108,6112,6121,6128,6137,6160,6169,6176,6264,6272,6276,
6279,6312,6314,6314,6320,6389,6400,6430,6470,6509,6512,6516,6528,6571,6576,6601,6608,6618,6656,6678,6688,6740,6784,6793,
6800,6809,6823,6823,6917,6963,6981,6988,6992,7001,7043,7072,7086,7141,7168,7203,7232,7241,7245,7293,7296,7306,7312,7354,
7357,7359,7401,7404,7406,7411,7413,7414,7418,7418,7424,7615,7680,7957,7960,7965,7968,8005,8008,8013,8016,8023,8025,8025,
8027,8027,8029,8029,8031,8061,8064,8116,8118,8124,8126,8126,8130,8132,8134,8140,8144,8147,8150,8155,8160,8172,8178,8180,
8182,8188,8304,8305,8308,8313,8319,8329,8336,8348,8450,8450,8455,8455,8458,8467,8469,8469,8473,8477,8484,8484,8486,8486,
8488,8488,8490,8493,8495,8505,8508,8511,8517,8521,8526,8526,8528,8585,9312,9371,9450,9471,10102,10131,11264,11492,11499,11502,
11506,11507,11517,11517,11520,11557,11559,11559,11565,11565,11568,11623,11631,11631,11648,11670,11680,11686,11688,11694,11696,11702,11704,11710,
11712,11718,11720,11726,11728,11734,11736,11742,11823,11823,12293,12295,12321,12329,12337,12341,12344,12348,12353,12438,12445,12447,12449,12538,
12540,12543,12549,12591,12593,12686,12690,12693,12704,12735,12784,12799,12832,12841,12872,12879,12881,12895,12928,12937,12977,12991,13312,19903,
19968,42124,42192,42237,42240,42508,42512,42539,42560,42606,42623,42653,42656,42735,42775,42783,42786,42888,42891,42957,42960,42961,42963,42963,
42965,42972,42994,43009,43011,43013,43015,43018,43020,43042,43056,43061,43072,43123,43138,43187,43216,43225,43250,43255,43259,43259,43261,43262,
43264,43301,43312,43334,43360,43388,43396,43442,43471,43481,43488,43492,43494,43518,43520,43560,43584,43586,43588,43595,43600,43609,43616,43638,
43642,43642,43646,43695,43697,43697,43701,43702,43705,43709,43712,43712,43714,43714,43739,43741,43744,43754,43762,43764,43777,43782,43785,43790,
43793,43798,43808,43814,43816,43822,43824,43866,43868,43881,43888,44002,44016,44025,44032,55203,55216,55238,55243,55291,63744,64109,64112,64217,
64256,64262,64275,64279,64285,64285,64287,64296,64298,64310,64312,64316,64318,64318,64320,64321,64323,64324,64326,64433,64467,64829,64848,64911,
64914,64967,65008,65019,65136,65140,65142,65276,65296,65305,65313,65338,65345,65370,65382,65470,65474,65479,65482,65487,65490,65495,65498,65500,
65536,65547,65549,65574,65576,65594,65596,65597,65599,65613,65616,65629,65664,65786,65799,65843,65856,65912,65930,65931,66176,66204,66208,66256,
66273,66299,66304,66339,66349,66378,66384,66421,66432,66461,66464,66499,66504,66511,66513,66517,66560,66717,66720,66729,66736,66771,66776,66811,
66816,66855,66864,66915,66928,66938,66940,66954,66956,66962,66964,66965,66967,66977,66979,66993,66995,67001,67003,67004,67008,67059,67072,67382,
67392,67413,67424,67431,67456,67461,67463,67504,67506,67514,67584,67589,67592,67592,67594,67637,67639,67640,67644,67644,67647,67669,67672,67702,
67705,67742,67751,67759,67808,67826,67828,67829,67835,67867,67872,67897,67968,68023,68028,68047,68050,68096,68112,68115,68117,68119,68121,68149,
68160,68168,68192,68222,68224,68255,68288,68295,68297,68324,68331,68335,68352,68405,68416,68437,68440,68466,68472,68497,68521,68527,68608,68680,
68736,68786,68800,68850,68858,68899,68912,68921,68928,68965,68975,68997,69216,69246,69248,69289,69296,69297,69314,69316,69376,69415,69424,69445,
69457,69460,69488,69505,69552,69579,69600,69622,69635,69687,69714,69743,69745,69746,69749,69749,69763,69807,69840,69864,69872,69881,69891,69926,
69942,69951,69956,69956,69959,69959,69968,70002,70006,70006,70019,70066,70081,70084,70096,70106,70108,70108,70113,70132,70144,70161,70163,70187,
70207,70208,70272,70278,70280,70280,70282,70285,70287,70301,70303,70312,70320,70366,70384,70393,70405,70412,70415,70416,70419,70440,70442,70448,
70450,70451,70453,70457,70461,70461,70480,70480,70493,70497,70528,70537,70539,70539,70542,70542,70544,70581,70583,70583,70609,70609,70611,70611,
70656,70708,70727,70730,70736,70745,70751,70753,70784,70831,70852,70853,70855,70855,70864,70873,71040,71086,71128,71131,71168,71215,71236,71236,
71248,71257,71296,71338,71352,71352,71360,71369,71376,71395,71424,71450,71472,71483,71488,71494,71680,71723,71840,71922,71935,71942,71945,71945,
71948,71955,71957,71958,71960,71983,71999,71999,72001,72001,72016,72025,72096,72103,72106,72144,72161,72161,72163,72163,72192,72192,72203,72242,
72250,72250,72272,72272,72284,72329,72349,72349,72368,72440,72640,72672,72688,72697,72704,72712,72714,72750,72768,72768,72784,72812,72818,72847,
72960,72966,72968,72969,72971,73008,73030,73030,73040,73049,73056,73061,73063,73064,73066,73097,73112,73112,73120,73129,73440,73458,73474,73474,
73476,73488,73490,73523,73552,73561,73648,73648,73664,73684,73728,74649,74752,74862,74880,75075,77712,77808,77824,78895,78913,78918,78944,82938,
82944,83526,90368,90397,90416,90425,92160,92728,92736,92766,92768,92777,92784,92862,92864,92873,92880,92909,92928,92975,92992,92995,93008,93017,
93019,93025,93027,93047,93053,93071,93504,93548,93552,93561,93760,93846,93952,94026,94032,94032,94099,94111,94176,94177,94179,94179,94208,100343,
100352,101589,101631,101640,110576,110579,110581,110587,110589,110590,110592,110882,110898,110898,110928,110930,110933,110933,110948,110951,110960,111355,113664,113770,
113776,113788,113792,113800,113808,113817,118000,118009,119488,119507,119520,119539,119648,119672,119808,119892,119894,119964,119966,119967,119970,119970,119973,119974,
119977,119980,119982,119993,119995,119995,119997,120003,120005,120069,120071,120074,120077,120084,120086,120092,120094,120121,120123,120126,120128,120132,120134,120134,
120138,120144,120146,120485,120488,120512,120514,120538,120540,120570,120572,120596,120598,120628,120630,120654,120656,120686,120688,120712,120714,120744,120746,120770,
120772,120779,120782,120831,122624,122654,122661,122666,122928,122989,123136,123180,123191,123197,123200,123209,123214,123214,123536,123565,123584,123627,123632,123641,
124112,124139,124144,124153,124368,124397,124400,124410,124896,124902,124904,124907,124909,124910,124912,124926,124928,125124,125127,125135,125184,125251,125259,125259,
125264,125273,126065,126123,126125,126127,126129,126132,126209,126253,126255,126269,126464,126467,126469,126495,126497,126498,126500,126500,126503,126503,126505,126514,
126516,126519,126521,126521,126523,126523,126530,126530,126535,126535,126537,126537,126539,126539,126541,126543,126545,126546,126548,126548,126551,126551,126553,126553,
126555,126555,126557,126557,126559,126559,126561,126562,126564,126564,126567,126570,126572,126578,126580,126583,126585,126588,126590,126590,126592,126601,126603,126619,
126625,126627,126629,126633,126635,126651,127232,127244,130032,130041,131072,173791,173824,177977,177984,178205,178208,183969,183984,191456,191472,192093,194560,195101,
196608,201546,201552,205743
];
function hasAlphanumeric(source) {
    if(/[A-Za-z0-9]/.test(source))return true;
    for(const char of source) {
        const value=char.codePointAt(0);let low=0,high=ALPHANUMERIC_RANGES.length/2;
        while(low<high) {
            const mid=(low+high)>>>1,start=ALPHANUMERIC_RANGES[2*mid],end=ALPHANUMERIC_RANGES[2*mid+1];
            if(value<start)high=mid;
            else if(value>end)low=mid+1;
            else return true;
        }
    }
    return false;
}
class RuntimeText {
    constructor(model) {
        this.model = model;
        const detailRows=model.detail_numeric||[],shadowed=new Set(detailRows.map(([pattern])=>pattern));
        const numericByPattern=new Map();
        const compileNumeric=([pattern,pair])=>{const expression=new RegExp('^(?:'+pattern+')$');numericByPattern.set(pattern,expression);return [expression,pair];};
        this.numeric = (model.numeric || []).filter(([pattern])=>!shadowed.has(pattern)).map(compileNumeric);
        this.rawNumeric = (model.raw_numeric || []).map(([pattern,pair])=>[new RegExp('^(?:'+pattern+')$'),pair]);
        this.producerNumeric = (model.producer_numeric || []).map(([pattern,pair,styles])=>[new RegExp('^(?:'+pattern+')$'),pair,styles]);
        this.detailNumeric = detailRows.map(compileNumeric);
        const inlineRows=model.detail_inline_icons||[];
        this.detailInlineIcons=inlineRows.map(([pattern,pair])=>[new RegExp(pattern,'g'),pair]);
        this.detailContexts=model.detail_contexts||{};
        this.detailJoin=model.detail_join||null;
        this.detailJoinLiterals=new Set(model.detail_join_literals||[]);
        const joinRows=(model.detail_join_numeric||[]).filter(pattern=>numericByPattern.has(pattern)).map(pattern=>[pattern,null]);
        this.detailJoinNumeric=joinRows.map(([pattern])=>[numericByPattern.get(pattern),null]);
        this.detailJoinNumericIndex=RuntimeText.numericIndex(this.detailJoinNumeric,joinRows);
        this.detailJoinCandidateCache=new Map();
        this.detailJoinBlockedLiterals=new Set(model.detail_join_blocked_literals||[]);
        const blockedJoinRows=(model.detail_join_blocked_numeric||[]).map(pattern=>[pattern,null]);
        this.detailJoinBlockedNumeric=blockedJoinRows.map(([pattern])=>[new RegExp('^(?:'+pattern+')$'),null]);
        this.detailJoinBlockedIndex=RuntimeText.numericIndex(this.detailJoinBlockedNumeric,blockedJoinRows);
        this.detailJoinBlockedCache=new Map();
        this.numericIndex=RuntimeText.numericIndex(this.numeric,model.numeric||[],shadowed);
        this.detailNumericIndex=RuntimeText.numericIndex(this.detailNumeric,detailRows);
        this.detailInlineIconIndex=RuntimeText.numericIndex(this.detailInlineIcons,inlineRows);
        this.numericCandidateCache=new Map();this.detailNumericCandidateCache=new Map();this.detailInlineIconCandidateCache=new Map();
        this.scoped = Object.fromEntries(Object.entries(model.scoped || {}).map(([k,v])=>[k,new RuntimeText(v)]));
        this.details = model.details ? new RuntimeText(model.details) : null;
        this.detailSources = new Set(model.detail_sources || []);
        this.detailHeaders = model.detail_headers || [];
        this.ambiguousDisplay = new Set(model.ambiguous_display || []);
        this.cache = new Map();
        this.planCache = new Map();
        this.speakerCache = new Map();
        this.historyCache = new Map();
        this.keyed = Object.fromEntries(Object.entries(model.keyed || {}).map(([k,v])=>[k,{source:v.source,tr:new RuntimeText(v.model)}]));
    }
    static numericLiteral(pattern) {
        const captures=['([+-]?\\d+)','([^<>\\r\\n]{1,512}?)'],runs=[];let run='';
        for(let at=0;at<pattern.length;) {
            const capture=captures.find(value=>pattern.startsWith(value,at));
            if(capture){if(run)runs.push(run);run='';at+=capture.length;continue;}
            const value=pattern[at++];
            if(value==='\\') {
                if(at>=pattern.length)return null;
                const escaped=pattern[at++];
                if(/[A-Za-z0-9]/.test(escaped))return null;
                run+=escaped;continue;
            }
            if('^$.*+?()[]{}|'.includes(value))return null;
            run+=value;
        }
        if(run)runs.push(run);
        return runs.sort((a,b)=>b.length-a.length||a.localeCompare(b))[0]||null;
    }
    static numericIndex(compiled,rows,excluded=new Set()) {
        const fallback=[],byFirst=new Map();let at=0;
        for(const row of rows) {
            if(excluded.has(row[0]))continue;
            const rule=compiled[at++],literal=RuntimeText.numericLiteral(row[0]),entry={at:at-1,rule};
            if(!literal){fallback.push(entry);continue;}
            const first=Array.from(literal)[0];
            if(!byFirst.has(first))byFirst.set(first,new Map());
            const bucket=byFirst.get(first);
            if(!bucket.has(literal))bucket.set(literal,[]);
            bucket.get(literal).push(entry);
        }
        return {fallback,byFirst};
    }
    static numericCandidates(source,index,cache) {
        if(cache.has(source))return cache.get(source);
        const selected=index.fallback.slice();
        for(const first of new Set(Array.from(source))) {
            const bucket=index.byFirst.get(first);if(!bucket)continue;
            for(const [literal,entries] of bucket)if(source.includes(literal))selected.push(...entries);
        }
        selected.sort((a,b)=>a.at-b.at);const result=selected.map(entry=>entry.rule);
        if(cache.size>=20000)cache.clear();cache.set(source,result);return result;
    }
    static renderFormat(template,replacement) {
        return template.replace(PRINTF_TOKEN,token=>token==='%%'?'%':replacement(token));
    }
    speakerContext(name,source) {
        const models=this.model.speaker_contexts||{};
        if(!Object.hasOwn(models,name))return null;
        const selected=models[name],body=source.replace(/^(?:<#[^<>]*>)+/,'');
        if(!Object.hasOwn(selected.pairs,source)&&!Object.hasOwn(selected.pairs,body))return null;
        if(!this.speakerCache.has(name))this.speakerCache.set(name,{tr:new RuntimeText(selected)});
        return this.speakerCache.get(name);
    }
    historyContext(name,source,kind='body') {
        const model=this.model.history_contexts;if(!model)return null;
        const body=kind==='name'?source:source.replace(/^(?:<#[^<>]*>)+/,'');
        const shared=kind==='name'?model.names:model.texts;
        if(!shared||!Object.hasOwn(shared,body))return null;
        let index=shared[body];
        const narrowed=kind==='body'&&Object.hasOwn(model.speakers||{},name)?model.speakers[name]:null;
        if(index<0&&narrowed&&Object.hasOwn(narrowed,body))index=narrowed[body];
        // Only copied history without a resolved script identity reaches this
        // fallback. Keep the exact index ambiguous; selecting an official
        // candidate for display must never create a dialogue identity.
        let fallback=false;
        if(index<0) {
            const candidates=kind==='name'?model.fallback_names:model.fallback_texts;
            const speaker=kind==='body'?model.fallback_speakers?.[name]:null;
            const selected=speaker&&Object.hasOwn(speaker,body)?speaker[body]:candidates?.[body];
            if(Number.isInteger(selected)&&selected>=0){index=selected;fallback=true;}
        }
        const key=JSON.stringify([kind,body,index,fallback]);
        if(!this.historyCache.has(key)) {
            const pair=Number.isInteger(index)&&index>=0?model.pairs[index]:null;
            const local=pair?{pairs:{[body]:pair},plain_pairs:{[body]:pair},same_language:model.same_language}:
                {pairs:{},plain_pairs:{},ambiguous_display:[body]};
            if(this.historyCache.size>=2048)this.historyCache.clear();
            this.historyCache.set(key,{tr:new RuntimeText(local),strict:true,fallback});
        }
        return this.historyCache.get(key);
    }
    literalArgument(source,side) {
        // String slots have no independent identity for punctuation-only lines.
        if(!hasAlphanumeric(source))return source;
        // String slots may hold lists, but must never recursively match printf.
        if(this.ambiguousDisplay.has(source))return source;
        if(Object.hasOwn(this.model.pairs,source))return this.model.pairs[source][side];
        const pairs=this.model.plain_pairs;
        if(Object.hasOwn(pairs,source))return pairs[source][side];
        let parts=source.split(COMPONENT_SEPARATORS);
        if(parts.length===1)parts=source.split(COMPONENT_LINKS);
        if(parts.length===1)return source;
        return parts.map((part,i)=>i%2?part:this.literalArgument(part,side)).join('');
    }
    pair(source) {
        const producer=this.producerPair(source);if(producer)return producer;
        if (Object.hasOwn(this.model.plain_pairs,source)) return this.model.plain_pairs[source];
        const parts=source.split(COMPONENT_LINKS);
        const pairs=parts.filter((_,i)=>!(i%2)).map(part=>
            !hasAlphanumeric(part)?null:
            Object.hasOwn(this.model.pairs,part)?this.model.pairs[part]:
            Object.hasOwn(this.model.plain_pairs,part)?this.model.plain_pairs[part]:null);
        if(parts.length>1&&pairs.every(Boolean))
            return [0,1].map(side=>parts.map((part,i)=>i%2?part:pairs[i/2][side]).join(''));
        let authoritative=null;
        for(const [pattern,pair] of RuntimeText.numericCandidates(source,this.detailNumericIndex,this.detailNumericCandidateCache)) {
            const m=pattern.exec(source);if(!m||m[0]!==source)continue;
            const rendered=pair.map(target=>{let i=1;return RuntimeText.renderFormat(target,()=>m[i++]);});
            if(authoritative&&JSON.stringify(authoritative)!==JSON.stringify(rendered))return null;
            authoritative=rendered;
        }
        if(authoritative)return authoritative;
        const literal=new Map(),freeform=new Map();
        for(const [pattern,pair] of RuntimeText.numericCandidates(source,this.numericIndex,this.numericCandidateCache)) {
            const m=pattern.exec(source);
            if(!m || m[0]!==source)continue;
            const rendered=pair.map((target,side)=>{
                let i=1;
                return RuntimeText.renderFormat(target,token=>{
                    const v=m[i++];return token.endsWith('s')?this.literalArgument(v,side):v;
                });
            });
            const stringSlots=(pair[0].match(PRINTF_TOKEN)||[]).some(token=>token.endsWith('s'));
            (stringSlots?freeform:literal).set(JSON.stringify(rendered),rendered);
        }
        const selected=literal.size?literal:freeform;
        return selected.size===1?selected.values().next().value:null;
    }
    static rubyRanges(source) {
        if(!source.includes('<R')&&!source.includes('</R'))return [];
        const ranges=[];let at=0;
        while(at<source.length) {
            const opening=source.indexOf('<R>',at),closing=source.indexOf('</R',at);
            if(closing>=0&&(opening<0||closing<opening))return null;
            if(opening<0)return source.includes('<R',at)?null:ranges;
            const closeStart=source.indexOf('</R',opening+3);
            if(closeStart<0)return null;
            const nested=source.indexOf('<R',opening+3);
            if(nested>=0&&nested<closeStart)return null;
            const closeEnd=source.indexOf('>',closeStart+3);
            if(closeEnd<0)return null;
            ranges.push([opening,closeEnd+1]);at=closeEnd+1;
        }
        return ranges;
    }
    static overlaps(span,ranges) {return ranges.some(([start,end])=>span[0]<end&&start<span[1]);}
    hasDetailContext(source,description) {
        const values=this.detailContexts[description]||{},ranges=RuntimeText.rubyRanges(source);
        if(ranges===null)return false;
        return Object.keys(values).some(span=>{
            let at=source.indexOf(span);while(at>=0) {if(!RuntimeText.overlaps([at,at+span.length],ranges))return true;at=source.indexOf(span,at+span.length);}return false;
        });
    }
    detailJoinPair(source) {
        if(!this.detailJoin)return null;
        const [separator,...targets]=this.detailJoin,short=separator.trimEnd();
        const partialTail=Boolean(short&&short!==separator&&source.endsWith(short)&&!source.endsWith(separator));
        const expanded=partialTail?source+separator.slice(short.length):source,parts=expanded.split(separator);
        if(parts.length<2||!parts.some(Boolean)||parts.slice(1,-1).some(part=>!part))return null;
        const pairs=parts[0]?[]:[['','']],stop=parts.length-(parts[parts.length-1]?0:1);
        let start=parts[0]?0:1;
        while(start<stop) {
            let matched=false;
            // Prefer an entire proven constructor to shorter labels.
            for(let end=stop;end>start;end--) {
                const member=parts.slice(start,end).join(separator);
                if(this.detailJoinBlockedLiterals.has(member)||RuntimeText.numericCandidates(member,this.detailJoinBlockedIndex,this.detailJoinBlockedCache).some(([pattern])=>pattern.test(member)))return null;
                if(this.ambiguousDisplay.has(member)||!(this.detailJoinLiterals.has(member)||
                    RuntimeText.numericCandidates(member,this.detailJoinNumericIndex,this.detailJoinCandidateCache).some(([pattern])=>pattern.test(member))))continue;
                const pair=this.pair(member);
                if(pair){pairs.push(pair);start=end;matched=true;break;}
            }
            if(!matched)return null;
        }
        if(!parts[parts.length-1])pairs.push(['','']);
        return targets.map((target,side)=>{
            let value=pairs.map(pair=>pair[side]).join(target);
            if(partialTail&&target!==target.trimEnd())value=value.slice(0,-target.length)+target.trimEnd();
            return value;
        });
    }
    componentParts(source) {
        const parts=source.split(COMPONENT_SEPARATORS);
        if(this.detailJoin) {
            const separator=this.detailJoin[0];let at=1;
            while(at<parts.length-1) {
                if(parts[at]!==separator){at+=2;continue;}
                let end=at;while(end+2<parts.length&&parts[end+2]===separator)end+=2;
                const combined=parts.slice(at-1,end+2).join('');
                if(this.detailJoinPair(combined))parts.splice(at-1,end-at+3,combined);
                else at=end+2;
            }
        }
        return parts.length===1?source.split(COMPONENT_LINKS):parts;
    }
    replaceDetailContext(source,mode,description) {
        const values=this.detailContexts[description]||{},ranges=RuntimeText.rubyRanges(source);
        if(ranges===null)return source;
        const selected=[];
        for(const [span,pair] of Object.entries(values)) {
            const target=pair[mode==='secondary'?1:0];
            for(let at=source.indexOf(span);at>=0;at=source.indexOf(span,at+span.length))
                if(!RuntimeText.overlaps([at,at+span.length],ranges))selected.push({start:at,end:at+span.length,target});
        }
        selected.sort((a,b)=>a.start-b.start||a.end-b.end);
        if(selected.some((row,index)=>index&&selected[index-1].end>row.start))return source;
        for(let at=selected.length-1;at>=0;at--) {const row=selected[at];source=source.slice(0,row.start)+row.target+source.slice(row.end);}
        return source;
    }
    hasDetailInlineIcon(source) {
        const ranges=RuntimeText.rubyRanges(source);if(ranges===null)return false;
        for(const [pattern] of RuntimeText.numericCandidates(source,this.detailInlineIconIndex,this.detailInlineIconCandidateCache)) {
            pattern.lastIndex=0;
            for(let match;(match=pattern.exec(source));) {
                if(!RuntimeText.overlaps([match.index,match.index+match[0].length],ranges))return true;
                if(!match[0].length)break;
            }
        }
        return false;
    }
    replaceDetailInlineIcons(source,mode) {
        const ranges=RuntimeText.rubyRanges(source);if(ranges===null)return source;
        const matches=new Map();
        for(const [pattern,pair] of RuntimeText.numericCandidates(source,this.detailInlineIconIndex,this.detailInlineIconCandidateCache)) {
            pattern.lastIndex=0;
            for(let match;(match=pattern.exec(source));) {
                const target=pair[mode==='secondary'?1:0];let at=1;
                const rendered=RuntimeText.renderFormat(target,()=>match[at++]);
                const key=match.index+'\x00'+(match.index+match[0].length);
                if(!matches.has(key))matches.set(key,{start:match.index,end:match.index+match[0].length,values:new Set()});
                matches.get(key).values.add(rendered);
                if(!match[0].length)break;
            }
        }
        const conflicting=[...matches.values()].filter(row=>row.values.size!==1);
        const selected=[...matches.values()].filter(row=>row.values.size===1&&
            !conflicting.some(other=>row.start<other.end&&other.start<row.end)&&
            !RuntimeText.overlaps([row.start,row.end],ranges)).sort((a,b)=>a.start-b.start||a.end-b.end);
        if(selected.some((row,index)=>index&&selected[index-1].end>row.start))return source;
        for(let at=selected.length-1;at>=0;at--) {
            const row=selected[at],value=row.values.values().next().value;
            source=source.slice(0,row.start)+value+source.slice(row.end);
        }
        return source;
    }
    anchoredDetails(source) {
        if(!this.details)return null;
        // The description retains its exact effect-record context even when
        // a header can independently authorize the detail labels.
        for(let at=source.indexOf('\n');at>=0;at=source.indexOf('\n',at+1)) {
            let suffix=source.slice(at+1);
            for(let controls=0;controls<16;controls++) {
                if(this.detailSources.has(suffix))return [this.details,suffix];
                const control=/^<\/?[Cc][0-9a-fA-F]*>|^<\/?B>|^<[sS]\d+>/.exec(suffix);
                if(!control)break;
                suffix=suffix.slice(control[0].length);
            }
        }
        return this.detailHeader(source)!==null?[this.details,'']:null;
    }
    detailHeader(source) {
        const original=source.split(/\r\n|\n|\\n/)[0];
        let header=original.replace(/(?:<\/[Cc]>|<\/B>)+$/,'');
        for(let i=0;i<16;i++) {
            if(this.detailHeaders.some(([prefix,suffix])=>header.startsWith(prefix)&&header.endsWith(suffix)&&header.length>=prefix.length+suffix.length))
                return original;
            const control=/^(?:<\/?[Cc][0-9a-fA-F]*>|<\/?B>|<[sS]\d+>)/.exec(header);
            if(!control)break;
            header=header.slice(control[0].length);
        }
        return null;
    }
    rawPair(source) {
        if(Object.hasOwn(this.model.pairs,source))return this.model.pairs[source];
        // Preserve layout-owned size controls around a complete known literal.
        // Do not use a stripped fragment or a generic printf match as identity.
        const size=/^(?:<[sS]\d+>)+/.exec(source);
        if(size) {
            const body=source.slice(size[0].length);
            if(Object.hasOwn(this.model.pairs,body))return this.model.pairs[body].map(target=>size[0]+target);
        }
        const producer=this.producerPair(source);if(producer)return producer;
        if(!source.includes('<'))return null;
        let found=null;
        for(const [pattern,pair] of this.rawNumeric) {
            const m=pattern.exec(source);if(!m||m[0]!==source)continue;
            const rendered=pair.map((target,side)=>{
                let i=1;return RuntimeText.renderFormat(target,token=>{
                    const v=m[i++];return token.endsWith('s')?this.literalArgument(v,side):v;
                });
            });
            if(found&&JSON.stringify(found)!==JSON.stringify(rendered))return null;found=rendered;
        }
        return found;
    }
    producerPair(source,rules=this.producerNumeric) {
        let found=null;
        for(const [pattern,pair,styles] of rules) {
            const m=pattern.exec(source);if(!m||m[0]!==source)continue;
            const values=m.slice(1).map(value=>value.replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xfee0)));
            if(values.some(value=>Number(value)<-2147483648||Number(value)>2147483647))continue;
            const rendered=pair.map((target,side)=>{
                let i=0;return RuntimeText.renderFormat(target,()=>{
                    const value=values[i],style=styles[side][i++];
                    return style==='fullwidth'?value.replace(/[0-9]/g,c=>String.fromCharCode(c.charCodeAt(0)+0xfee0)):value;
                });
            });
            if(found&&JSON.stringify(found)!==JSON.stringify(rendered))return null;found=rendered;
        }
        return found;
    }
    static ruby(a,b) {
        if(!a||!b)return a;
        if(!RuntimeText.needsAnnotation(a,b))return a;
        const sameCjk=a===b && /[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]/.test(a);
        if(a===b&&!sameCjk)return a;
        if(/[<>]/.test(a+b))return null;
        const left=a.replace(/\\n/g,'\n').split(/(\r\n|\n)/),right=b.replace(/\\n/g,'\n').split(/\r\n|\n/);
        if((left.length+1)/2!==right.length || left.some((v,i)=>!(i%2)&&Boolean(v.trim())!==Boolean(right[i/2].trim())))return null;
        return left.map((v,i)=>i%2?v:RuntimeText.needsAnnotation(v,right[i/2])?'<R>'+v+'</R'+right[i/2]+'>':v).join('');
    }
    static needsAnnotation(a,b) {
        // Native ruby readings are displayed text, not formatting. Equal Latin
        // bases can carry different translated readings in </R...>.
        const visible=s=>s.replace(/<\/R([^<>]*)>/g,'\x00$1').replace(/<[^<>]*>/g,'').replace(/[\uff01-\uff5e]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xfee0)).trim();
        const left=visible(a),right=visible(b);
        return !!left&&!!right&&(left!==right||/[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]/.test(left));
    }
    static visualSecondary(text) {
        return text.replace(/<[^<>]*>/g,t=>/^(?:<R>|<\/R[^<>]*>|<\/?[Cc][0-9a-fA-F]*>|<\/?B>|<[sS]\d+>|<I\d+>)$/.test(t)?t:'');
    }
    static closeColours(text) {
        let depth=0;for(const t of text.match(/<\/?[Cc][0-9a-fA-F]*>/g)||[])depth=t.startsWith('</')?Math.max(0,depth-1):depth+1;
        return '</C>'.repeat(depth);
    }
    static byteLength(text) {
        let n=0;for(const ch of text) {const c=ch.codePointAt(0);n+=c<128?1:c<2048?2:c<65536?3:4;}return n;
    }
    static latinWordCharacter(value) {
        return /^[A-Za-z0-9\u00c0-\u024f]$/.test(value);
    }
    static secondaryText(lines) {
        const result=[];
        for(const line of lines) {
            const last=result.at(-1);
            if(last&&line&&RuntimeText.latinWordCharacter(last.at(-1))&&RuntimeText.latinWordCharacter(line[0]))result.push(' ');
            result.push(line);
        }
        return result.join('');
    }
    static secondaryUnits(text) {
        const result=[],characterAt=at=>String.fromCodePoint(text.codePointAt(at));
        for(let at=0;at<text.length;) {
            if(text.startsWith('<R>',at)) {
                const close=text.indexOf('</R',at+3);if(close<0)return null;
                const end=text.indexOf('>',close);if(end<0)return null;
                const value=text.slice(at,end+1),base=text.slice(at+3,close);
                result.push({value,width:Array.from(base).filter(character=>!/^\s$/u.test(character)).length,tag:false});at=end+1;continue;
            }
            if(text[at]==='<') {
                const tag=/^<[^<>]*>/.exec(text.slice(at));
                if(!tag||!/^<\/?[Cc][0-9a-fA-F]*>$|^<\/?B>$|^<[sS]\d+>$|^<I\d+>$/.test(tag[0]))return null;
                result.push({value:tag[0],width:0,tag:true});at+=tag[0].length;continue;
            }
            let end=at+characterAt(at).length;
            if(RuntimeText.latinWordCharacter(characterAt(at))) {
                while(end<text.length&&RuntimeText.latinWordCharacter(characterAt(end)))end+=characterAt(end).length;
                while(end<text.length&&"'’‐-".includes(characterAt(end))&&end+characterAt(end).length<text.length&&RuntimeText.latinWordCharacter(characterAt(end+characterAt(end).length))) {
                    end+=characterAt(end).length;while(end<text.length&&RuntimeText.latinWordCharacter(characterAt(end)))end+=characterAt(end).length;
                }
            }
            const value=text.slice(at,end);result.push({value,width:Array.from(value).filter(character=>!/^\s$/u.test(character)).length,tag:false});at=end;
        }
        return result;
    }
    static reflowSecondaryParagraph(text,capacities) {
        const units=RuntimeText.secondaryUnits(text);if(units===null)return null;
        const result=[],state={colours:[],bold:false,size:''};
        const update=tag=>{
            if(/^<[Cc][0-9a-fA-F]*>$/.test(tag))state.colours.push(tag);
            else if(tag==='</C>'){if(state.colours.length)state.colours.pop();}
            else if(tag==='<B>')state.bold=true;
            else if(tag==='</B>')state.bold=false;
            else if(/^<[sS]\d+>$/.test(tag))state.size=tag;
        };
        const prefix=()=>state.colours.join('')+(state.bold?'<B>':'')+state.size;
        const close=()=>(state.bold?'</B>':'')+'</C>'.repeat(state.colours.length);
        const startsPunctuation=()=>{
            for(const unit of units)if(unit.width)return '、。！？）】》〉」』〕］｝'.includes(Array.from(unit.value.replace(/<[^<>]*>/g,''))[0]);
            return false;
        };
        const take=line=>{const unit=units.shift();line.push(unit.value);if(unit.tag)update(unit.value);return unit.width;};
        for(let number=0;number<capacities.length;number++) {
            if(!capacities[number]) {
                // No annotation can attach to an icon/control-only line.
                const line=[prefix()];while(units.length&&units[0].tag)take(line);
                result.push(line.join('')+close());continue;
            }
            if(!capacities.slice(number+1).some(Boolean)){const line=[prefix()];while(units.length)take(line);result.push(line.join('')+close());continue;}
            while(result.length&&units.length&&units[0].width&&/^\s$/u.test(units[0].value))result[result.length-1]+=units.shift().value;
            const line=[prefix()];let used=0;
            const remainingCapacity=capacities.slice(number).reduce((sum,value)=>sum+value,0);
            const remainingText=units.reduce((sum,unit)=>sum+unit.width,0);
            const target=Math.max(1,Math.ceil(remainingText*capacities[number]/remainingCapacity));
            while(units.length&&(!line.length||used<target))used+=take(line);
            while(units.length&&units[0].tag&&['</C>','</B>'].includes(units[0].value))take(line);
            while(units.length&&startsPunctuation())used+=take(line);
            result.push(line.join('')+close());
        }
        return result;
    }
    static reflowAnnotationLines(primary,secondary) {
        const left=primary.split(/\r\n|\n|\\n/),right=secondary.split(/\r\n|\n|\\n/),result=Array(left.length).fill('');
        const paragraphs=lines=>{
            const groups=[],current=[];
            lines.forEach((line,index)=>{
                if(line.trim()) {
                    if(current.length&&/^\s/u.test(line))groups.push(current.splice(0));
                    current.push([index,line]);
                } else if(current.length) groups.push(current.splice(0));
            });
            if(current.length)groups.push(current);return groups;
        };
        const leftGroups=paragraphs(left),rightGroups=paragraphs(right);
        if(!leftGroups.length)return result;
        const groups=leftGroups.length===rightGroups.length
            ?leftGroups.map((group,index)=>[group,rightGroups[index]])
            :[[[].concat(...leftGroups),[].concat(...rightGroups)]];
        for(const [leftGroup,rightGroup] of groups) {
            const text=RuntimeText.secondaryText(rightGroup.map(([,line])=>line));
            const capacities=leftGroup.map(([,line])=>Array.from(line.replace(/<[^<>]*>/g,'')).filter(char=>!/\s/u.test(char)).length);
            const reflowed=RuntimeText.reflowSecondaryParagraph(text,capacities);if(reflowed===null)return null;
            reflowed.forEach((value,index)=>{result[leftGroup[index][0]]=value;});
        }
        return result;
    }
    static annotationPlan(a,b) {
        const left=a.split(/(\r\n|\n|\\n)/),visible=RuntimeText.visualSecondary(b);let right=visible.split(/\r\n|\n|\\n/);
        const count=(left.length+1)/2;
        const needsReflow=count!==right.length||left.some((v,i)=>!(i%2)&&Boolean(v.trim())!==Boolean(right[i/2]?.trim()));
        if(needsReflow||(visible.includes('<')&&count>1)) {
            const reflowed=RuntimeText.reflowAnnotationLines(a,visible);
            if(reflowed!==null)right=reflowed;
            else if(needsReflow) {
                const payload=right.join(' '),anchor=left.findIndex((v,i)=>!(i%2)&&v.trim());
                right=Array(count).fill('');right[Math.max(0,anchor/2)]=payload;
            }
        } else if(count===1)right[0]+=RuntimeText.closeColours(right[0]);
        let text='';const layers=[];
        left.forEach((part,i)=>{
            if(i%2){text+=part;return;}
            const payload=right[i/2];
            if(RuntimeText.needsAnnotation(part,payload)) {
                layers.push({offset:RuntimeText.byteLength(text)+6,text:payload,primary:part,protected:a.includes('<R>')||b.includes('<R>')});
                text+='<R></R_>';
            }
            text+=part;
        });
        return {text,layers,kind:'layered'};
    }
    render(source,mode='annotation',key='',scope='') {
        // Older resident adapters request bilingual for cutscene labels.
        // Keep that wire value compatible, but use annotations everywhere.
        if(mode==='bilingual')mode='annotation';
        if(this.model.same_language&&mode==='annotation')mode='primary';
        const ck=mode+'\x00'+key+'\x00'+scope+'\x00'+source;
        if(this.planCache.has(ck))return this.planCache.get(ck);
        const header=this.details?this.detailHeader(source):null;
        if(mode==='annotation'&&header!==null) {
            // Keep header labels separate from the body's rich-text lane:
            // icon/count arguments never become secondary annotation text.
            let text=this.details.translate(header,mode),layers=[];
            const rest=source.slice(header.length),separator=/^(?:\r\n|\n|\\n)/.exec(rest);
            if(separator) {
                text+=separator[0];
                const body=this.render(rest.slice(separator[0].length),mode,key,scope),offset=RuntimeText.byteLength(text);
                layers=body.layers.map(layer=>({...layer,offset:layer.offset+offset}));text+=body.text;
            }
            const result={text,layers,kind:layers.length?'layered':text.includes('<R>')?'ruby':'plain'};
            if(this.planCache.size>=20000)this.planCache.clear();this.planCache.set(ck,result);return result;
        }
        const a=this.translate(source,'primary',key,scope),b=this.translate(source,'secondary',key,scope);
        if(mode==='annotation'&&(!RuntimeText.needsAnnotation(a,b)||
                (a===source&&b===source&&this.ambiguousDisplay.has(source.replace(/^(?:<#[^<>]*>)+/,''))))) {
            const result={text:a,layers:[],kind:'plain'};
            if(this.planCache.size>=20000)this.planCache.clear();this.planCache.set(ck,result);return result;
        }
        let result;
        const anchored=this.anchoredDetails(source);
        const known=this.rawPair(source)!==null||
            this.rawPair(source.replace(/^(?:<#[^<>]*>)+/,''))!==null||
            Boolean(anchored&&anchored[0].hasDetailInlineIcon(source))||
            Boolean(anchored&&anchored[0].hasDetailContext(source,anchored[1]))||
            Boolean(anchored&&anchored[0].detailJoinIconRuns(source))||
            (Object.hasOwn(this.keyed,key)&&this.keyed[key].source===source);
        const prefix=(a.match(/^(?:<#[^<>]*>)*/)||[''])[0],body=a.slice(prefix.length),visibleB=RuntimeText.visualSecondary(b);
        if(mode==='annotation'&&known&&!/[<>]/.test(body+visibleB)&&
                body.split(/\r\n|\n|\\n/).length===visibleB.split(/\r\n|\n|\\n/).length) {
            const value=RuntimeText.ruby(body,visibleB);
            if(value!==null) {
                const text=prefix+value;
                result={text,layers:[],kind:text!==source?'ruby':'plain'};
                if(this.planCache.size>=20000)this.planCache.clear();this.planCache.set(ck,result);return result;
            }
        }
        const left=a.split(/\r\n|\n|\\n/),right=b.split(/\r\n|\n|\\n/);
        const differentLines=left.length!==right.length||left.some((v,i)=>Boolean(v.trim())!==Boolean(right[i]?.trim()));
        if(mode==='annotation'&&((known&&(/[<>]/.test(a+b)||differentLines))||(a!==b&&((a+b).includes('<R>')||differentLines)))&&RuntimeText.visualSecondary(b).trim())
            result=RuntimeText.annotationPlan(a,b);
        else {
            const text=this.translate(source,mode,key,scope);
            result={text,layers:[],kind:mode==='annotation'&&text!==source&&text.includes('<R>')?'ruby':'plain'};
        }
        if(this.planCache.size>=20000)this.planCache.clear();this.planCache.set(ck,result);return result;
    }
    component(source,mode) {
        // Complete dialogue/keyed pairs were resolved before decomposition.
        if(!hasAlphanumeric(source))return source;
        // Icon counts and other numeric-only runs retain their native form.
        if(/[0-9０-９]/.test(source)&&/^[\s×+−\-0-9０-９.,，．%％]+$/.test(source))return source;
        const literal=Object.hasOwn(this.model.plain_pairs,source)?this.model.plain_pairs[source]:null;
        const pair=this.detailJoin?(literal||this.detailJoinPair(source)||this.pair(source)):this.pair(source);
        if(pair) {
            const [a,b]=pair;
            if(mode==='primary')return a;
            if(mode==='secondary')return b;
            const value=RuntimeText.ruby(a,b);if(value!==null)return value;
        }
        const trimmed=source.trim();
        if(trimmed&&trimmed!==source) {
            const inner=this.component(trimmed,mode);
            if(inner!==trimmed) {const at=source.indexOf(trimmed);return source.slice(0,at)+inner+source.slice(at+trimmed.length);}
        }
        // Middle dots join inline lists of any length, not just bullets.
        // Whole resource pairs above retain priority over decomposition.
        const parts=this.componentParts(source);
        if(parts.length>1)return parts.map((p,i)=>i%2?p:this.component(p,mode)).join('');
        return source;
    }
    translate(source,mode='annotation',key='',scope='',detailContext='') {
        if(this.model.same_language&&mode==='annotation')mode='primary';
        const ck=mode+'\x00'+key+'\x00'+scope+'\x00'+detailContext+'\x00'+source;
        if(this.cache.has(ck))return this.cache.get(ck);
        const result=this.resolve(source,mode,key,scope,detailContext);
        if(this.cache.size>=20000)this.cache.clear();
        this.cache.set(ck,result);return result;
    }
    detailJoinIconRuns(source) {
        if(!(this.detailJoin&&source.includes('<I')&&!source.includes('<R>')&&source.includes(this.detailJoin[0])&&!this.rawPair(source)))return null;
        const runs=source.split(/(<\/?[Cc][0-9a-fA-F]*>|<[sS]\d+>|\r\n|\n|\\n)/),joined=new Set();
        runs.forEach((run,index)=>{if(!(index%2)&&run.includes('<I')&&this.detailJoinPair(run))joined.add(index);});
        return joined.size?[runs,joined]:null;
    }
    resolve(source,mode,key,scope,detailContext='') {
        if(mode==='bilingual')mode='annotation';
        if(source.length>16384)return source;
        const keyed=Object.hasOwn(this.keyed,key)?this.keyed[key]:null;
        if(keyed && keyed.source===source) return keyed.tr.translate(source,mode);
        if(scope&&this.scoped[scope]) {
            const t=this.scoped[scope].translate(source,mode);if(t!==source)return t;
        }
        const anchored=this.anchoredDetails(source);
        if(anchored)return anchored[0].translate(source,mode,'','',anchored[1]);
        if(detailContext)source=this.replaceDetailContext(source,mode,detailContext);
        const joinedRuns=this.detailJoinIconRuns(source);
        if(joinedRuns) {
            const [runs,joined]=joinedRuns;
            if(joined.size)return runs.map((run,index)=>{
                if(index%2)return run;
                if(joined.has(index))return this.component(run,mode);
                if(this.detailInlineIcons.length)run=this.replaceDetailInlineIcons(run,mode);
                return run.split(/(<[^<>]*>|\r\n|\n|\\n)/).map((part,offset)=>offset%2?part:this.component(part,mode)).join('');
            }).join('');
        }
        if(this.detailInlineIcons.length)source=this.replaceDetailInlineIcons(source,mode);
        if(this.ambiguousDisplay.has(source)||this.ambiguousDisplay.has(source.replace(/^(?:<#[^<>]*>)+/,'')))return source;
        const pair=this.rawPair(source);
        if(pair&&(mode==='primary'||mode==='secondary'))return pair[mode==='primary'?0:1];
        const controls=/^(?:<#[^<>]*>)+/.exec(source);
        if(controls)return controls[0]+this.translate(source.slice(controls[0].length),mode);
        if(source.includes('<R>')) {
            const parts=source.split(/(<#[^<>]*>|\r\n|\n|\\n)/);
            return parts.length>1?parts.map((t,i)=>i%2?t:this.translate(t,mode)).join(''):source;
        }
        if(!/[<>]/.test(source)) {const t=this.component(source,mode);if(t!==source)return t;}
        return source.split(/(<[^<>]*>|\r\n|\n|\\n)/).map((t,i)=>i%2?t:this.component(t,mode)).join('');
    }
}
if(typeof module!=='undefined')module.exports={RuntimeText};
