"""Export Unicode Line_Break properties from Windows ICU into shared data.

No download, package installation, game access or outside-project write.
The committed ranges let Python, Node and Frida use the same Unicode version.
"""

import ctypes
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def main():
    icu = ctypes.CDLL("icu.dll")
    property_enum = icu.u_getPropertyEnum
    property_enum.argtypes, property_enum.restype = [ctypes.c_char_p], ctypes.c_int
    get_value = icu.u_getIntPropertyValue
    get_value.argtypes, get_value.restype = [ctypes.c_int, ctypes.c_int], ctypes.c_int
    get_name = icu.u_getPropertyValueName
    get_name.argtypes, get_name.restype = (
        [ctypes.c_int, ctypes.c_int, ctypes.c_int],
        ctypes.c_char_p,
    )
    version = (ctypes.c_uint8 * 4)()
    icu.u_getUnicodeVersion(version)
    property_id = property_enum(b"Line_Break")
    if property_id < 0:
        raise RuntimeError("ICU Line_Break property unavailable")
    names, ranges = {}, []
    for point in range(0x110000):
        value = get_value(point, property_id)
        if value not in names:
            names[value] = get_name(property_id, value, 0).decode("ascii")
        if ranges and ranges[-1][2] == names[value]:
            ranges[-1][1] = point
        else:
            ranges.append([point, point, names[value]])
    metadata = {
        "source": "Windows ICU Unicode Line_Break property",
        "unicode_version": ".".join(str(n) for n in list(version)[:3]),
        "ranges": ranges,
    }
    path = ROOT / "sora_bilingual/localization/annotation_break_data.json"
    path.write_text(json.dumps(metadata, separators=(",", ":")) + "\n", encoding="utf-8")
    js = ROOT / "sora_bilingual/game/scripts/runtime_text.js"
    source = js.read_text("utf-8")
    source, count = re.subn(
        r"// BEGIN ANNOTATION BREAK DATA\n.*?// END ANNOTATION BREAK DATA",
        "// BEGIN ANNOTATION BREAK DATA\n// Unicode "
        + metadata["unicode_version"]
        + "; generated by tools/generate_annotation_break_data.py.\nconst ANNOTATION_BREAK_RANGES="
        + json.dumps(ranges, separators=(",", ":"))
        + ";\n// END ANNOTATION BREAK DATA",
        source,
        flags=re.S,
    )
    if count != 1:
        raise RuntimeError("shared JS data marker missing or duplicated")
    js.write_text(source, encoding="utf-8")
    print(json.dumps({"unicode_version": metadata["unicode_version"], "ranges": len(ranges)}))


if __name__ == "__main__":
    main()
